amend! Update to v3.16.2
lualanes: Update to v3.16.2

Update the PKG_VERSION to pull version 3.16.2 from upstream. This includes fixes for the `pthread_yield: symbol not found` issue.

Build tested and confirmed on x86_64.

Signed-off-by: Mark Baker <mark@vpost.net>