lualanes: Version bump to v3.16.2
Update the PKG_VERSION to pull version 3.16.2 from upstream. The upstream
version includes fixes for the `pthread_yield: symbol not found` issue.

Removed patch 200-fix-redef-error.patch as the fix was implemented
upstream.

Build tested and confirmed on x86_64.

Signed-off-by: Mark Baker <mark@vpost.net>